apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset-config
  namespace: raphaelasilva
data:
  dataset.yaml: |
    dataset:
      name: 2023_spotify_ds1.csv
      path: /playlists/2023_spotify_ds1.csv
      date: 2023-11-03
