apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset-config
  namespace: raphaelasilva
data:
  dataset.yaml: |
    dataset:
      name: 2023_spotify_ds2.csv
      path: /playlists/2023_spotify_ds2.csv
      date: 2023-11-02
