apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-frontend
  namespace: raphaelasilva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-recommendor
  template:
    metadata:
      labels:
        app: playlist-recommendor
    spec:
      containers:
      - name: frontend
        image: raphahausen/frontend-playlist:0.2
        ports:
        - containerPort: 50025
        volumeMounts:
        - name: pickles-volume
          mountPath: /app
      volumes:
      - name: pickles-volume
        hostPath:
          path: /home/raphaelasilva/project2-pv
          type: DirectoryOrCreate

