apiVersion: batch/v1
kind: Job
metadata:
  name: ml-playlist-job
  namespace: raphaelasilva
spec:
  template:
    metadata:
      labels:
        app: ml-recommendor
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ml-playlist-generator
        image: raphahausen/ml-playlist-generator:0.2
        volumeMounts:
        - name: pickles-volume
          mountPath: /app
        - name: datasets-volume
          mountPath: /playlists
        - name: dataset-config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: pickles-volume
        hostPath:
          path: /home/raphaelasilva/project2-pv
          type: DirectoryOrCreate
      - name: datasets-volume
        hostPath:
          path: /home/datasets/spotify
          type: Directory
      - name: dataset-config-volume
        configMap:
          name: dataset-config
