apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment
  namespace: raphaelasilva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-recommendor
  template:
    metadata:
      labels:
        app: ml-recommendor
      annotations:
        # Alterar este valor (por exemplo, data do dataset) força a recriação do Pod
        dataset-version: "2025-11-04"
    spec:
      restartPolicy: Always
      containers:
      - name: ml-playlist-generator
        image: raphahausen/ml-playlist-generator:2.3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"   # memória mínima garantida
            cpu: "500m"       # 0.5 vCPU garantido
          limits:
            memory: "2Gi"     # limite máximo de 2GB para evitar OOMKilled
            cpu: "1"          # até 1 CPU
        volumeMounts:
        - name: pickles-volume
          mountPath: /app
        - name: datasets-volume
          mountPath: /playlists
        - name: dataset-config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: pickles-volume
        hostPath:
          path: /home/raphaelasilva/project2-pv
          type: DirectoryOrCreate
      - name: datasets-volume
        hostPath:
          path: /home/datasets/spotify
          type: Directory
      - name: dataset-config-volume
        configMap:
          name: dataset-config
