apiVersion: batch/v1
kind: Job
metadata:
  name: ml-job
  namespace: raphaelasilva
  argocd.argoproj.io/sync-options: "CreateOnly=true"  # ArgoCD não tenta recriar
spec:
  ttlSecondsAfterFinished: 60   # o Job será removido 60s após terminar
  template:
    metadata:
      labels:
        app: ml-recommendor
      annotations:
        dataset-version: "2025-11-01"
    spec:
      restartPolicy: Never       # Job não deve reiniciar em caso de sucesso/falha
      containers:
      - name: ml-playlist-generator
        image: raphahausen/ml-playlist-generator:3.4
        imagePullPolicy: Always
        volumeMounts:
        - name: pickles-volume
          mountPath: /app
        - name: datasets-volume
          mountPath: /playlists
        - name: dataset-config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: pickles-volume
        hostPath:
          path: /home/raphaelasilva/project2-pv
          type: DirectoryOrCreate
      - name: datasets-volume
        hostPath:
          path: /home/datasets/spotify
          type: Directory
      - name: dataset-config-volume
        configMap:
          name: dataset-config
